version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Checking connection to the S3 Dependency Warehouse..."
      - aws s3 ls s3://vladan-dependency-repo

  build:
    commands:
      - echo "====== BEGINNING TEST PHASE ======"
      - echo "Running tests on `date`"
      - chmod +x run-tests.sh
      - ./run-tests.sh
      - echo "====== TEST PHASE COMPLETE ======"
      - echo "====== BEGINNING BUILD PHASE ======"
      - echo "Build started on `date`"
      - mvn -s settings.xml compile
      - echo "====== BUILD PHASE COMPLETE ======"

  post_build:
    commands:
      - echo "Packaging the final product..."
      - mvn -s settings.xml package
      
artifacts:
  files:
    - target/devops-challenge.war
  discard-paths: no